---
# Uninstall i3-wm


- name: Ensure packages are uninstalled
  apt: pkg={{item}} force=yes state=absent
  with_items:
   - i3-wm

- name: Remove autostart entries
  file: src={{item}} dest=/home/{{remote_user}}/.config/autostart/ state=absent
  with_fileglob:
    - autostart/*

- name: Delete session cache
  file: path=/home/{{remote_user}}/.cache/sessions state=absent

- name: Restore xfce4 session config
  shell: cp /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml /home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml

- name: Enable xfce4-wm
  lineinfile: dest=/usr/share/applications/xfce-wm-settings.desktop state=absent line="Hidden=true"

- name: Remove i3 config
  file: path=/home/{{remote_user}}/.i3 state=absent
